### ISSUE TITLE
Add some way to change the content of the close button

### ISSUE THREAD

**Issue by mkjems** [HugoGiraudel/react-a11y-dialog#15]
At the moment a hardcoded ```&times;``` is used in all cases.
It would be nice to be able to change this via a prop.

**Comment by HugoGiraudel** [comment]
True. Do you feel like submitting a PR? :)

**Comment by HugoGiraudel** [comment]
Done in 1.2.1: https://github.com/HugoGiraudel/react-a11y-dialog/releases/tag/1.2.1.
