### ISSUE TITLE
How to open modal on page load?

### ISSUE THREAD

**Issue by CerritosWebMaster** [HugoGiraudel/react-a11y-dialog#17]
Hi,

I am new to GitHub.  Our web administrator recently retired and we have not obtained a new one; I know some web basics so I found your many resources through Google.  Thanks!

I implemented code found here: https://codepen.io/HugoGiraudel/pen/jWQqeq on our server because we need an accessible modal window containing a form.  You can see it here: http://cms.cerritos.edu/public-affairs/default-3.htm.

Question is, how to make the modal popup on page load and how to make form check appear within the modal window.

Thanks.

**Comment by HugoGiraudel** [comment]
Hello,

Are you using react-a11y-dialog (React), or just a11y-dialog? In the second case, this is not the correct repository. This repository is for the React wrapper for a11y-dialog.

If you are simply using a11y-dialog, you can do something like this:

```js
(function () {
  document.addEventListener('DOMContentLoaded', function () {
    var modalEl = document.getElementById('my-accessible-modal');
    var modal = new window.Modal(modalEl);
   
    modal.shot()
  });
}());
```

You should probably use the versioned and up-to-date code from https://github.com/edenspiekermann/a11y-dialog rather than this obsolete outdated CodePen. 

Also, I would advise again opening a dialog on page load. Dialogs are extremely intrusive and should only be open on user interaction. 

I hope it helps.

**Comment by CerritosWebMaster** [comment]
Hello Hugo,

Thank you for your prompt reply.  Initially, I implemented the a11y-dialog here: http://cms.cerritos.edu/public-affairs/default-1.htm.  However, you can see that when I add additional fields, all of the fields stay inline and get pushed off to the right.  Additionally, the top header gets pushed down about an inch or so.

[cid:image003.jpg@01D31CB3.C06785D0]

Regards,
Samuel Chavez
Web Support Technician
Cerritos College - Office of Public Affairs
(562) 860-2451, Ext. 2966
schavez@cerritos.edu<mailto:schavez@cerritos.edu>

**Comment by HugoGiraudel** [comment]
Hey,

I am very sorry but I cannot take time to help you sort out this issue, unless this is any relevant to a11y-dialog or react-a11y-dialog (in other words, if you found a bug).

Regarding making the dialog appear on load, if you still want to do that, the code I provided above should work. For your CSS problem, I recommend you reach out to public forums for support such as StackOverflow or CSS-Tricks.

Best.

**Comment by scsskid** [comment]
using the hook its a no brainer, because you got the instance by destructuring

`const [instance] = useA11yDialog({ })`

But with the component I ended up using local state, I didnt want to lift the ref or state to parents

My solution (Using React router 6)
**See the `dialogRef` init fn**

```jsx
import React, { useEffect, useRef, useState } from 'react';
import { A11yDialog } from 'react-a11y-dialog';
import { useParams } from 'react-router-dom';

export default function ProjectSingle() {
  const dialog = useRef();
  const [instance, setInstance] = useState();
  const { projectSlug } = useParams();

  useEffect(() => {
    if (!instance) return;

    instance.show();
  }, [instance, projectSlug]);

  return (
    <>
      <A11yDialog
        id="my-accessible-dialog"
        dialogRef={(instance) => {
          dialog.current = instance;
          setInstance(instance);
        }}
        title="The dialog title"
        classNames={{
          container: 'dialog-container',
          overlay: 'dialog-overlay',
          dialog: 'dialog-content',
          title: 'dialog-title',
          closeButton: 'dialog-close'
        }}
      >
        <p>Some content for the dialog.</p>
      </A11yDialog>
    </>
  );
}
```

**Comment by KittyGiraudel** [comment]
That’s still the way to go. I still highly discourage opening a dialog on page load, or in any way that’s not direcly initiated by the user.
