### ISSUE TITLE
Cannot read property 'destroy' of undefined

### ISSUE THREAD

**Issue by timarney** [HugoGiraudel/react-a11y-dialog#25]
I'm running into an issue where the code is throwing an error but only for minified build code.

Where would be the best place to add a check or ensure the dialog exists before calling destroy?

<img width="762" alt="screen shot 2018-05-31 at 1 37 07 pm" src="https://user-images.githubusercontent.com/62242/40797948-c9a1a992-64d7-11e8-88c0-ec95efc06325.png">

<hr>
<img width="386" alt="screen shot 2018-05-31 at 1 36 31 pm" src="https://user-images.githubusercontent.com/62242/40797956-cf1bde6a-64d7-11e8-923c-38d957449a89.png">

**Comment by HugoGiraudel** [comment]
Hello Tim.

It should be fixed in 3.0.6. :)
