### ISSUE TITLE
Server Side Rendering

### ISSUE THREAD

**Issue by pascalduez** [HugoGiraudel/react-a11y-dialog#26]
Hi,

correct me if I'm wrong but actually the mere fact of requiring the lib breaks any server bundle since `a11y-dialog` uses directly `document`.

```
ReferenceError: document is not defined                                                                                     
at node_modules/a11y-dialog/a11y-dialog.js:19:37                                                        
[...]                                                                                                                                                                                        
```

Trying to find some workarounds right now.

**Comment by HugoGiraudel** [comment]
Interesting. We don’t have the problem at all at N26, even though we have an isomorphic application.

**Comment by HugoGiraudel** [comment]
It should be fixed with https://github.com/HugoGiraudel/react-a11y-dialog/releases/tag/4.0.1. My bad!
