### ISSUE TITLE
Migrate to React hooks

### ISSUE THREAD

**Issue by nik72619c** [HugoGiraudel/react-a11y-dialog#31]
@HugoGiraudel

**Comment by HugoGiraudel** [comment]
Why?

**Comment by nik72619c** [comment]
This might not be dead important but :-
1. React hooks are new so a functional component can be powered with hooks, having the same functionalities of a class component. Also, the functional components are more optimised performance-wise than class components.
2. Hooks are new, so migrating to a newer version might pose out to be a better option
3. Functional components are easier to test

**Comment by HugoGiraudel** [comment]
This probably won’t happen before the next major refactor of the lib. I’m going to close for now. :)
