### ISSUE TITLE
Prevent `role="alertdialog"` and <dialog> from being used together

### ISSUE THREAD

**Issue by HugoGiraudel** [HugoGiraudel/react-a11y-dialog#45]
See https://github.com/edenspiekermann/a11y-dialog/issues/115.

**Comment by morkro** [comment]
What should the response be if someone uses both together? If `role="alertdialog"` is being used with `<dialog>`, convert it to `<div>` and `console.warn` it to the user?

**Comment by HugoGiraudel** [comment]
I’m not too sure. We could:
- Throw with an explanation.
- Keep `role="alertdialog"` and swap to `<div>`.
- Keep `<dialog>` and swap to `role="dialog"`, but it makes less sense.

**Comment by morkro** [comment]
Yeah, I think setting `role` is more of a conscious choice so I would prioritise that. But throwing could also be a good option as it forces the user to change something. A warning can be ignored.

**Comment by HugoGiraudel** [comment]
Done with #52.
